import { useEffect,useMemo,useState } from "react";
import { useInfiniteQuery,useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { BarChart3,Download,FlaskConical,FolderOpen,History,LayoutDashboard,Pencil,Search,Settings,Trash2,Users,X } from "lucide-react";
import { api,ImportPreview } from "./api";
import { changeMetric,validInstagramUsername } from "./presentation";
import { ResultsTable } from "./ResultsTable";

const kinds=[['followers','Followers'],['following','Following'],['mutuals','Mutuals'],['not_following_back','Not following back'],['followers_not_followed_back','Followers you do not follow']] as const;
type View='overview'|'lists'|'changes'|'history'|'settings'|'fame';
const message=(e:unknown)=>typeof e==='string'?e:e instanceof Error?e.message:'Something went wrong';
const today=()=>new Date().toISOString().slice(0,10);
const onboardingKey='nivune-onboarded',legacyOnboardingKey='insight-onboarded';

function BrandMark(){return <svg className="brand-eye" viewBox="0 0 120 80" role="img" aria-label="Data iris logo"><path d="M5 40C20 16 38 6 60 6s40 10 55 34C100 64 82 74 60 74S20 64 5 40Z" fill="none" stroke="currentColor" strokeWidth="5"/><circle cx="60" cy="40" r="22" fill="#36b37e"/><path d="M47 49V37M56 49V27M65 49V33M74 49V22" stroke="#effff8" strokeWidth="5" strokeLinecap="round"/><circle cx="60" cy="40" r="29" fill="none" stroke="#8ee3bd" strokeWidth="2" strokeDasharray="3 5"/></svg>}

export default function App(){
 const qc=useQueryClient(),accounts=useQuery({queryKey:['accounts'],queryFn:api.accounts});
 const [accountId,setAccountId]=useState<number|null>(null),[snapshotId,setSnapshotId]=useState<number|null>(null),[kind,setKind]=useState('followers'),[changeDirection,setChangeDirection]=useState<string|null>(null),[search,setSearch]=useState(''),[view,setView]=useState<View>('overview'),[preview,setPreview]=useState<ImportPreview|null>(null),[importTarget,setImportTarget]=useState<'current'|'new'>('current'),[newLabel,setNewLabel]=useState(''),[ownerUsername,setOwnerUsername]=useState(''),[observedAt,setObservedAt]=useState(today()),[error,setError]=useState(''),[fromId,setFromId]=useState<number|null>(null),[detailUser,setDetailUser]=useState<string|null>(null),[backupPassphrase,setBackupPassphrase]=useState(''),[backupConfirmation,setBackupConfirmation]=useState(''),[onboarded,setOnboarded]=useState(()=>window.localStorage?.getItem(onboardingKey)==='1'||window.localStorage?.getItem(legacyOnboardingKey)==='1');
 const [debouncedSearch,setDebouncedSearch]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>setDebouncedSearch(search.trim()),250);return()=>clearTimeout(timer)},[search]);
 const currentId=accountId??accounts.data?.[0]?.id??null,account=accounts.data?.find(a=>a.id===currentId);
 const snapshots=useQuery({queryKey:['snapshots',currentId],queryFn:()=>api.snapshots(currentId!),enabled:!!currentId});
 useEffect(()=>{if(!snapshots.data)return;setSnapshotId(id=>id&&snapshots.data.some(s=>s.id===id)?id:snapshots.data[0]?.id??null)},[snapshots.data]);
 const selected=snapshots.data?.find(s=>s.id===snapshotId),selectedIndex=snapshots.data?.findIndex(s=>s.id===snapshotId)??-1,previous=snapshots.data?.[selectedIndex+1];
 useEffect(()=>{if(selected&&snapshots.data)setFromId(id=>id&&id!==selected.id&&snapshots.data!.some(s=>s.id===id)?id:previous?.id??null)},[selected?.id,previous?.id,snapshots.data]);
 const summary=useQuery({queryKey:['summary',currentId,selected?.id],queryFn:()=>api.summary(currentId!,selected?.id),enabled:!!selected});
 const trends=useQuery({queryKey:['trends',currentId],queryFn:()=>api.trends(currentId!),enabled:!!currentId&&view==='overview'});
 const rows=useInfiniteQuery({queryKey:['relationships',selected?.id,kind,debouncedSearch],queryFn:({pageParam})=>api.relationships(selected!.id,kind,debouncedSearch,pageParam),initialPageParam:null as string|null,getNextPageParam:last=>last.nextCursor,enabled:!!selected&&view==='lists'});
 const changes=useInfiniteQuery({queryKey:['changes',fromId,selected?.id,kind,changeDirection,debouncedSearch],queryFn:({pageParam})=>api.changes(fromId!,selected!.id,kind,debouncedSearch,pageParam,changeDirection),initialPageParam:null as string|null,getNextPageParam:last=>last.nextCursor,enabled:!!fromId&&!!selected&&view==='changes'});
 const fame=useQuery({queryKey:['fame-foundation'],queryFn:api.fameFoundationStatus,enabled:view==='fame'});
 const history=useQuery({queryKey:['relationship-history',currentId,detailUser],queryFn:()=>api.relationshipHistory(currentId!,detailUser!),enabled:!!currentId&&!!detailUser});
 const queryFailure=[accounts,snapshots,summary,trends,rows,changes,fame,history].find(q=>q.isError)?.error;
 useEffect(()=>{if(queryFailure)setError(message(queryFailure))},[queryFailure]);
 const inspect=useMutation({mutationFn:api.chooseImport,onSuccess:p=>{if(!p)return;setPreview(p);setImportTarget(currentId&&p.detectedUsername?'current':'new');setNewLabel(p.detectedUsername??'');setOwnerUsername(p.detectedUsername??'');setObservedAt(today());setError('')},onError:e=>setError(message(e))});
 const commit=useMutation({mutationFn:()=>api.commit(preview!.token,importTarget==='current'?currentId:null,newLabel||ownerUsername||'Imported account',ownerUsername,observedAt),onSuccess:async s=>{setPreview(null);setAccountId(s.accountId);setSnapshotId(s.id);setView('overview');await qc.invalidateQueries()},onError:e=>setError(message(e))});
 async function refresh(){await qc.invalidateQueries()}
 async function cancelPreview(){if(preview)await api.cancelImport(preview.token);setPreview(null)}
 async function exportRows(format:'csv'|'json'){if(!selected)return;if(view==='changes'&&!fromId){setError('Choose an earlier snapshot before exporting changes');return}try{view==='changes'?await api.exportChanges(fromId!,selected.id,kind,changeDirection,format):await api.exportReport(selected.id,kind,format)}catch(e){setError(message(e))}}
 async function rename(){if(!account)return;const label=prompt('Account label',account.label);if(label===null)return;try{await api.renameAccount(account.id,label);await refresh()}catch(e){setError(message(e))}}
 async function removeAccount(){if(!account||!confirm(`Delete “${account.label}” and all snapshots? This cannot be undone.`))return;try{await api.deleteAccount(account.id);setAccountId(null);setSnapshotId(null);await refresh()}catch(e){setError(message(e))}}
 async function removeSnapshot(id:number){if(!confirm('Delete this snapshot? This cannot be undone.'))return;try{await api.deleteSnapshot(id);if(snapshotId===id)setSnapshotId(null);await refresh()}catch(e){setError(message(e))}}
 async function createBackup(){if(backupPassphrase!==backupConfirmation){setError('Backup passphrases do not match');return}try{if(await api.createEncryptedBackup(backupPassphrase)){setBackupPassphrase('');setBackupConfirmation('');setError('Encrypted backup created successfully. Store its passphrase separately.')}}catch(e){setError(message(e))}}
 async function restoreBackup(){if(!confirm('Replace all local accounts and snapshots with this backup? This cannot be undone.'))return;try{if(await api.restoreEncryptedBackup(backupPassphrase)){setBackupPassphrase('');setAccountId(null);setSnapshotId(null);await refresh();setError('Encrypted backup restored successfully.')}}catch(e){setError(message(e))}}
 const relationshipRows=useMemo(()=>rows.data?.pages.flatMap(p=>p.items)??[],[rows.data]),changeRows=useMemo(()=>changes.data?.pages.flatMap(p=>p.items)??[],[changes.data]);
 const metrics=summary.data?[['Followers',summary.data.followers],['Following',summary.data.following],['Mutuals',summary.data.mutuals],['Not following back',summary.data.notFollowingBack],['You do not follow',summary.data.followersNotFollowedBack],['New / lost',changeMetric(summary.data.hasPreviousSnapshot,summary.data.newFollowers,summary.data.lostFollowers)]]:[];
 return <div className="shell"><aside><div className="brand"><BrandMark/><div><strong>Nivune</strong><span>Private audience memory</span></div></div><nav>
  <button className={view==='overview'?'active':''} onClick={()=>setView('overview')}><LayoutDashboard/>Overview</button><button className={view==='lists'?'active':''} onClick={()=>setView('lists')}><Users/>Relationships</button><button className={view==='changes'?'active':''} onClick={()=>setView('changes')}><History/>Changes</button><button className={view==='history'?'active':''} onClick={()=>setView('history')}><BarChart3/>History</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings/>Settings</button>
 </nav><div className="privacy">Local by default<br/><span>No login, scraping, or cloud upload</span></div></aside><main>
 <header><div><h1>{account?.label??'Your audience history'}</h1><p>{selected?`Observed ${new Date(`${selected.observedAt}T12:00:00`).toLocaleDateString()} · imported ${new Date(selected.importedAt).toLocaleDateString()}`:'Import an official data export to begin.'}</p></div><div className="actions">{accounts.data?.length?<select aria-label="Account" value={currentId??''} onChange={e=>{setAccountId(Number(e.target.value));setSnapshotId(null)}}>{accounts.data.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select>:null}{account&&<><button onClick={rename}><Pencil/>Rename</button><button className="danger" onClick={removeAccount}><Trash2/>Delete</button></>}<button onClick={()=>inspect.mutate(true)} disabled={inspect.isPending}><FolderOpen/>Folder</button><button className="primary" onClick={()=>inspect.mutate(false)} disabled={inspect.isPending}><FolderOpen/>Import ZIP</button></div></header>
 {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {preview&&<div className="notice import-preview"><div><strong>Ready to import {preview.sourceName}</strong><span>{preview.followers.toLocaleString()} followers · {preview.following.toLocaleString()} following</span></div><div className="actions"><input aria-label="Archive owner username" placeholder="Owner username" value={ownerUsername} readOnly={!!preview.detectedUsername} onChange={e=>setOwnerUsername(e.target.value)}/><label className="date-field"><span>Observed on</span><input aria-label="Observation date" type="date" max={today()} value={observedAt} onChange={e=>setObservedAt(e.target.value)}/></label>{currentId&&<select aria-label="Import destination" value={importTarget} onChange={e=>setImportTarget(e.target.value as 'current'|'new')}><option value="current">Add to selected account</option><option value="new">Create new account</option></select>}{importTarget==='new'&&<input aria-label="New account label" placeholder="Account label" value={newLabel} onChange={e=>setNewLabel(e.target.value)}/>}<button onClick={cancelPreview}>Cancel</button><button className="primary" onClick={()=>commit.mutate()} disabled={commit.isPending||!validInstagramUsername(ownerUsername)||!observedAt}>Confirm import</button></div></div>}
 {view==='overview'&&selected?<><section className="metrics">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><div className="panel-title"><div><h2>Audience trend</h2><p>Counts are ordered by the date you said each archive represents.</p></div></div><div className="trend" aria-label="Follower trend">{trends.data?.map((p,i,a)=>{const max=Math.max(...a.map(x=>x.followers),1);return <div className="trend-point" key={p.snapshotId} title={`${p.followers} followers on ${p.observedAt}`}><span style={{height:`${Math.max(8,p.followers/max*100)}%`}}/><small>{p.observedAt.slice(5)}</small></div>})}</div>{(trends.data?.length??0)<2&&<div className="empty compact">Import another archive later to reveal growth and churn.</div>}</section></>:null}
 {view==='lists'&&selected?<DataWorkspace mode="lists"/>:null}{view==='changes'&&selected?<><div className="smart-lists"><strong>Smart lists</strong><button onClick={()=>{setKind('followers');setChangeDirection('added')}}>New followers</button><button onClick={()=>{setKind('followers');setChangeDirection('removed')}}>Lost followers</button><button onClick={()=>{setKind('mutuals');setChangeDirection('added')}}>New mutuals</button><button onClick={()=>{setKind('mutuals');setChangeDirection('removed')}}>Lost mutuals</button><button onClick={()=>setChangeDirection(null)}>All changes</button></div><div className="comparison"><label><span>From</span><select aria-label="From snapshot" value={fromId??''} onChange={e=>setFromId(Number(e.target.value))}>{snapshots.data?.filter(s=>s.id!==selected.id).map(s=><option key={s.id} value={s.id}>{s.observedAt}</option>)}</select></label><span>→</span><label><span>To</span><select aria-label="To snapshot" value={selected.id} onChange={e=>setSnapshotId(Number(e.target.value))}>{snapshots.data?.map(s=><option key={s.id} value={s.id}>{s.observedAt}</option>)}</select></label></div><DataWorkspace mode="changes"/></>:null}
 {view==='history'&&<section className="panel history-list"><h2>Snapshot history</h2>{snapshots.data?.map(s=><div className={s.id===snapshotId?'selected':''} key={s.id}><button className="snapshot-select" onClick={()=>setSnapshotId(s.id)}><strong>{s.observedAt}</strong><span>{s.followers.toLocaleString()} followers · {s.following.toLocaleString()} following · imported {new Date(s.importedAt).toLocaleDateString()}</span>{s.observedAtSource==='legacy_import_time'&&<em>Date inferred from the old import time</em>}</button><button title="Delete snapshot" onClick={()=>removeSnapshot(s.id)}><Trash2/></button></div>)}</section>}
 {view==='settings'&&<section className="panel settings"><h2>Privacy & product settings</h2><div className="setting"><div><strong>Usage analytics</strong><p>Disabled. No endpoint is configured and no usage event leaves this device.</p></div><span className="status-off">Off</span></div><div className="setting backup-setting"><div><strong>Portable encrypted backups</strong><p>Authenticated age encryption protects a complete, consistent copy of your local database. The passphrase cannot be recovered.</p><input type="password" minLength={12} maxLength={1024} autoComplete="new-password" aria-label="Backup passphrase" placeholder="Backup passphrase (12+ characters)" value={backupPassphrase} onChange={e=>setBackupPassphrase(e.target.value)}/><input type="password" minLength={12} maxLength={1024} autoComplete="new-password" aria-label="Confirm backup passphrase" placeholder="Confirm passphrase when creating" value={backupConfirmation} onChange={e=>setBackupConfirmation(e.target.value)}/></div><div className="actions"><button disabled={backupPassphrase.length<12||backupPassphrase!==backupConfirmation} onClick={createBackup}>Create backup</button><button className="danger" disabled={backupPassphrase.length<12} onClick={restoreBackup}>Restore backup</button></div></div><button onClick={()=>setView('fame')}><FlaskConical/>Open Fame research status</button></section>}
 {view==='fame'&&<section className="roadmap"><button onClick={()=>setView('settings')}>← Settings</button><h2>Fame privacy research</h2><p>Retrieval is intentionally unavailable.</p><div className="status-card"><strong>Validated foundations</strong><ul>{fame.data?.completedFoundations.map(x=><li key={x}>{x}</li>)}</ul></div><div className="status-card blocked"><strong>Blocked production gates</strong><ul>{fame.data?.blockedGates.map(x=><li key={x}>{x}</li>)}</ul></div></section>}
 {!selected&&view!=='settings'&&view!=='fame'?<section className="welcome"><BarChart3/><h2>Build a private record of your audience</h2><p>Import complete official exports over time. Everything stays on this device.</p></section>:null}
 {detailUser&&<aside className="drawer" aria-label="Relationship history"><button className="drawer-close" aria-label="Close details" onClick={()=>setDetailUser(null)}><X/></button><h2>@{detailUser}</h2><p>Relationship state across observed snapshots</p>{history.data?.map(point=><div className="history-point" key={point.snapshotId}><strong>{point.observedAt}</strong><span>{point.followsYou?'Follows you':'Does not follow you'} · {point.youFollow?'You follow':'You do not follow'}</span></div>)}</aside>}
 {!onboarded&&<div className="onboarding" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div><BrandMark/><h2 id="onboarding-title">Your private audience memory</h2><p>Import official export files without logging in. Archives, relationship history, searches, and analytics remain on this device.</p><ul><li>No Instagram credentials or profile scraping</li><li>Confirm the date each archive represents</li><li>Create an encrypted backup before relying on long-term history</li></ul><button className="primary" onClick={()=>{window.localStorage?.setItem(onboardingKey,'1');setOnboarded(true)}}>Continue</button></div></div>}
 </main></div>;

 function DataWorkspace({mode}:{mode:'lists'|'changes'}){const data=mode==='changes'?changeRows:relationshipRows,query=mode==='changes'?changes:rows;return <section className="workspace"><div className="toolbar"><div className="tabs">{kinds.map(([id,label])=><button className={kind===id?'active':''} onClick={()=>{setKind(id);if(mode==='changes')setChangeDirection(null)}} key={id}>{label}</button>)}</div><div className="tools"><label><Search/><input maxLength={30} aria-label="Search username" placeholder="Search username" value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={()=>exportRows('csv')}><Download/>CSV</button><button onClick={()=>exportRows('json')}><Download/>JSON</button></div></div><ResultsTable mode={mode} hasPreviousSnapshot={mode==='lists'||!!fromId} relationships={mode==='lists'?data as never:[]} changes={mode==='changes'?data as never:[]} hasNextPage={!!query.hasNextPage} isFetchingNextPage={query.isFetchingNextPage} onLoadMore={()=>void query.fetchNextPage()} onSelect={setDetailUser}/></section>}
}
