import { useMemo,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { open,save } from "@tauri-apps/plugin-dialog";
import { BarChart3,Download,FolderOpen,History,Search,Trash2,Users } from "lucide-react";
import { api,ImportPreview } from "./api";

const kinds=[['followers','Followers'],['following','Following'],['mutuals','Mutuals'],['not_following_back','Not following back'],['followers_not_followed_back','Followers you do not follow']] as const;
const message=(e:unknown)=>typeof e==='string'?e:e instanceof Error?e.message:'Something went wrong';

export default function App(){
 const qc=useQueryClient(), accounts=useQuery({queryKey:['accounts'],queryFn:api.accounts});
 const [accountId,setAccountId]=useState<number|null>(null),[kind,setKind]=useState('followers'),[search,setSearch]=useState(''),[view,setView]=useState<'lists'|'changes'>('lists'),[preview,setPreview]=useState<ImportPreview|null>(null),[error,setError]=useState('');
 const currentId=accountId??accounts.data?.[0]?.id??null;
 const snapshots=useQuery({queryKey:['snapshots',currentId],queryFn:()=>api.snapshots(currentId!),enabled:!!currentId});
 const current=snapshots.data?.[0]; const previous=snapshots.data?.[1];
 const summary=useQuery({queryKey:['summary',currentId,current?.id],queryFn:()=>api.summary(currentId!,current?.id),enabled:!!current});
 const rows=useQuery({queryKey:['relationships',current?.id,kind,search],queryFn:()=>api.relationships(current!.id,kind,search),enabled:!!current&&view==='lists'});
 const changes=useQuery({queryKey:['changes',previous?.id,current?.id],queryFn:()=>api.changes(previous!.id,current!.id),enabled:!!previous&&!!current&&view==='changes'});
 const inspect=useMutation({mutationFn:api.inspect,onSuccess:p=>{setPreview(p);setError('')},onError:e=>setError(message(e))});
 const commit=useMutation({mutationFn:()=>api.commit(preview!.token,currentId,preview!.detectedUsername??'Instagram account'),onSuccess:async()=>{setPreview(null);await qc.invalidateQueries()},onError:e=>setError(message(e))});
 async function chooseImport(directory=false){const path=await open(directory?{multiple:false,directory:true}:{multiple:false,directory:false,filters:[{name:'Instagram export',extensions:['zip','json']} ]});if(path)inspect.mutate(path as string)}
 async function exportRows(format:'csv'|'json'){if(!current)return;const path=await save({defaultPath:`insight-${kind}.${format}`,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(path)await api.exportReport(current.id,kind,format,path)}
 const filteredChanges=useMemo(()=>changes.data?.filter(x=>x.category===kind&&(search===''||x.username.toLowerCase().includes(search.toLowerCase())))??[],[changes.data,kind,search]);
 const metrics=summary.data?[['Followers',summary.data.followers],['Following',summary.data.following],['Mutuals',summary.data.mutuals],['Not following back',summary.data.notFollowingBack],['You do not follow',summary.data.followersNotFollowedBack],['New / lost',`${summary.data.newFollowers} / ${summary.data.lostFollowers}`]]:[];
 return <div className="shell"><aside><div className="brand"><svg className="brand-eye" viewBox="0 0 120 80" role="img" aria-label="insIGht eye logo"><defs><linearGradient id="brand-ig" x1="0" y1="1" x2="1" y2="0"><stop stopColor="#ff7a00"/><stop offset=".45" stopColor="#e1306c"/><stop offset="1" stopColor="#833ab4"/></linearGradient></defs><path d="M4 40C18 15 37 4 60 4s42 11 56 36c-14 25-33 36-56 36S18 65 4 40Z" fill="#fffafd" stroke="#e1306c" strokeWidth="4"/><rect x="36" y="16" width="48" height="48" rx="14" fill="url(#brand-ig)"/><rect x="45" y="25" width="30" height="30" rx="9" fill="none" stroke="#fff" strokeWidth="3.5"/><circle cx="60" cy="40" r="7" fill="none" stroke="#fff" strokeWidth="3.5"/><circle cx="70" cy="30" r="2.2" fill="#fff"/></svg><div><strong>insIGht</strong><span>Relationship analytics</span></div></div><nav><button className={view==='lists'?'active':''} onClick={()=>setView('lists')}><Users/>Accounts</button><button className={view==='changes'?'active':''} onClick={()=>setView('changes')}><History/>Changes</button></nav><div className="privacy">Local data only<br/><span>No Instagram connection</span></div></aside>
 <main><header><div><h1>{accounts.data?.find(a=>a.id===currentId)?.label??'Your Instagram data'}</h1><p>{current?`Imported ${new Date(current.importedAt).toLocaleString()}`:'Import an official Instagram JSON export to begin.'}</p></div><div className="actions">{accounts.data?.length?<select aria-label="Account" value={currentId??''} onChange={e=>setAccountId(Number(e.target.value))}>{accounts.data.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select>:null}<button onClick={()=>chooseImport(true)} disabled={inspect.isPending}><FolderOpen/>Folder</button><button className="primary" onClick={()=>chooseImport()} disabled={inspect.isPending}><FolderOpen/>Import file</button></div></header>
 {error&&<div className="notice error">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {preview&&<div className="notice"><div><strong>Ready to import {preview.sourceName}</strong><span>{preview.followers.toLocaleString()} followers, {preview.following.toLocaleString()} following{preview.warnings.length?` · ${preview.warnings.join(' · ')}`:''}</span></div><div><button onClick={()=>setPreview(null)}>Cancel</button><button className="primary" onClick={()=>commit.mutate()} disabled={commit.isPending}>Confirm import</button></div></div>}
 {current?<><section className="metrics">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="workspace"><div className="toolbar"><div className="tabs">{kinds.map(([id,label])=><button className={kind===id?'active':''} onClick={()=>setKind(id)} key={id}>{label}</button>)}</div><div className="tools"><label><Search/><input placeholder="Search username" value={search} onChange={e=>setSearch(e.target.value)}/></label><button title="Export CSV" onClick={()=>exportRows('csv')}><Download/>CSV</button><button title="Export JSON" onClick={()=>exportRows('json')}><Download/>JSON</button></div></div>
 <div className="table"><div className="thead"><span>Account</span><span>{view==='changes'?'Change':'Relationship'}</span></div>{view==='changes'&&!previous?<div className="empty">Import another snapshot to see changes.</div>:(view==='changes'?filteredChanges:rows.data??[]).map((r:any)=><div className="tr" key={`${r.username}-${r.direction??''}`}><div className="account"><div className="avatar">{r.username.slice(0,2).toUpperCase()}</div><div><strong>@{r.username}</strong>{r.profileUrl&&<a href={r.profileUrl}>View profile</a>}</div></div><span className={`badge ${r.direction??''}`}>{r.direction??kinds.find(x=>x[0]===r.kind)?.[1]??r.kind}</span></div>)}{(view==='lists'&&rows.data?.length===0)||(view==='changes'&&previous&&filteredChanges.length===0)?<div className="empty">No matching accounts.</div>:null}</div></section>
 <section className="snapshots"><h2>Import history</h2>{snapshots.data?.map(s=><div key={s.id}><span><strong>{new Date(s.importedAt).toLocaleString()}</strong> {s.followers} followers · {s.following} following</span><button title="Delete snapshot" onClick={async()=>{if(confirm('Delete this snapshot?')){await api.deleteSnapshot(s.id);await qc.invalidateQueries()}}}><Trash2/></button></div>)}</section></>:<section className="welcome"><BarChart3/><h2>Your audience, clearly mapped</h2><p>Import a JSON archive from Instagram Accounts Center. Your data stays on this device.</p><div className="actions"><button onClick={()=>chooseImport(true)}><FolderOpen/>Choose folder</button><button className="primary" onClick={()=>chooseImport()}><FolderOpen/>Choose file</button></div></section>}</main></div>
}
