import { useEffect,useMemo,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { BarChart3,Download,FolderOpen,History,Pencil,Search,Sparkles,Trash2,Users } from "lucide-react";
import { api,ImportPreview } from "./api";
import { changeMetric,matchesUsername,validInstagramUsername } from "./presentation";

const kinds=[['followers','Followers'],['following','Following'],['mutuals','Mutuals'],['not_following_back','Not following back'],['followers_not_followed_back','Followers you do not follow']] as const;
type View='lists'|'changes'|'fame';
const message=(e:unknown)=>typeof e==='string'?e:e instanceof Error?e.message:'Something went wrong';

export default function App(){
 const qc=useQueryClient(),accounts=useQuery({queryKey:['accounts'],queryFn:api.accounts});
 const [accountId,setAccountId]=useState<number|null>(null),[snapshotId,setSnapshotId]=useState<number|null>(null),[kind,setKind]=useState('followers'),[search,setSearch]=useState(''),[view,setView]=useState<View>('lists'),[preview,setPreview]=useState<ImportPreview|null>(null),[importTarget,setImportTarget]=useState<'current'|'new'>('current'),[newLabel,setNewLabel]=useState(''),[ownerUsername,setOwnerUsername]=useState(''),[error,setError]=useState('');
 const currentId=accountId??accounts.data?.[0]?.id??null;
 const account=accounts.data?.find(a=>a.id===currentId);
 const snapshots=useQuery({queryKey:['snapshots',currentId],queryFn:()=>api.snapshots(currentId!),enabled:!!currentId});
 useEffect(()=>{if(!snapshots.data)return;setSnapshotId(id=>id&&snapshots.data.some(s=>s.id===id)?id:snapshots.data[0]?.id??null)},[snapshots.data]);
 const selected=snapshots.data?.find(s=>s.id===snapshotId);
 const selectedIndex=snapshots.data?.findIndex(s=>s.id===snapshotId)??-1;
 const previous=selectedIndex>=0?snapshots.data?.[selectedIndex+1]:undefined;
 const summary=useQuery({queryKey:['summary',currentId,selected?.id],queryFn:()=>api.summary(currentId!,selected?.id),enabled:!!selected});
 const rows=useQuery({queryKey:['relationships',selected?.id,kind,search],queryFn:()=>api.relationships(selected!.id,kind,search),enabled:!!selected&&view==='lists'});
 const changes=useQuery({queryKey:['changes',previous?.id,selected?.id],queryFn:()=>api.changes(previous!.id,selected!.id),enabled:!!previous&&!!selected&&view==='changes'});
 const fame=useQuery({queryKey:['fame-foundation'],queryFn:api.fameFoundationStatus,enabled:view==='fame'});
 const inspect=useMutation({mutationFn:api.chooseImport,onSuccess:p=>{if(!p)return;setPreview(p);setImportTarget(currentId&&p.detectedUsername?'current':'new');setNewLabel(p.detectedUsername??'');setOwnerUsername(p.detectedUsername??'');setError('')},onError:e=>setError(message(e))});
 const commit=useMutation({mutationFn:()=>api.commit(preview!.token,importTarget==='current'?currentId:null,newLabel||ownerUsername||'Instagram account',ownerUsername),onSuccess:async snapshot=>{setPreview(null);setAccountId(snapshot.accountId);setSnapshotId(snapshot.id);await qc.invalidateQueries()},onError:e=>setError(message(e))});
 async function refresh(){await qc.invalidateQueries()}
 async function chooseImport(directory=false){inspect.mutate(directory)}
 async function cancelPreview(){if(preview)await api.cancelImport(preview.token);setPreview(null)}
 async function exportRows(format:'csv'|'json'){if(!selected)return;if(view==='changes'&&!previous){setError('Select a snapshot with an immediately prior import before exporting changes');return}try{view==='changes'?await api.exportChanges(previous!.id,selected.id,kind,format):await api.exportReport(selected.id,kind,format)}catch(e){setError(message(e))}}
 async function rename(){if(!account)return;const label=prompt('Account label',account.label);if(label===null)return;try{await api.renameAccount(account.id,label);await refresh()}catch(e){setError(message(e))}}
 async function removeAccount(){if(!account||!confirm(`Delete “${account.label}” and all of its snapshots? This cannot be undone.`))return;try{await api.deleteAccount(account.id);setAccountId(null);setSnapshotId(null);await refresh()}catch(e){setError(message(e))}}
 async function removeSnapshot(id:number){if(!confirm('Delete this snapshot? This cannot be undone.'))return;try{await api.deleteSnapshot(id);if(snapshotId===id)setSnapshotId(null);await refresh()}catch(e){setError(message(e))}}
 const filteredChanges=useMemo(()=>changes.data?.filter(x=>x.category===kind&&matchesUsername(x.username,search))??[],[changes.data,kind,search]);
 const metrics=summary.data?[['Followers',summary.data.followers],['Following',summary.data.following],['Mutuals',summary.data.mutuals],['Not following back',summary.data.notFollowingBack],['You do not follow',summary.data.followersNotFollowedBack],['New / lost',changeMetric(summary.data.hasPreviousSnapshot,summary.data.newFollowers,summary.data.lostFollowers)]]:[];
 return <div className="shell"><aside><div className="brand"><svg className="brand-eye" viewBox="0 0 120 80" role="img" aria-label="insIGht eye logo"><defs><linearGradient id="brand-ig" x1="0" y1="1" x2="1" y2="0"><stop stopColor="#ff7a00"/><stop offset=".45" stopColor="#e1306c"/><stop offset="1" stopColor="#833ab4"/></linearGradient></defs><path d="M4 40C18 15 37 4 60 4s42 11 56 36c-14 25-33 36-56 36S18 65 4 40Z" fill="#fffafd" stroke="#e1306c" strokeWidth="4"/><rect x="36" y="16" width="48" height="48" rx="14" fill="url(#brand-ig)"/><rect x="45" y="25" width="30" height="30" rx="9" fill="none" stroke="#fff" strokeWidth="3.5"/><circle cx="60" cy="40" r="7" fill="none" stroke="#fff" strokeWidth="3.5"/><circle cx="70" cy="30" r="2.2" fill="#fff"/></svg><div><strong>insIGht</strong><span>Relationship analytics</span></div></div><nav><button className={view==='lists'?'active':''} onClick={()=>setView('lists')}><Users/>Accounts</button><button className={view==='changes'?'active':''} onClick={()=>setView('changes')}><History/>Changes</button><button className={view==='fame'?'active':''} onClick={()=>setView('fame')}><Sparkles/>Fame roadmap</button></nav><div className="privacy">Archives stay local<br/><span>Fame retrieval is unavailable</span></div></aside>
 <main><header><div><h1>{account?.label??'Your Instagram data'}</h1><p>{selected?`Imported ${new Date(selected.importedAt).toLocaleString()}`:'Import an official Instagram JSON export to begin.'}</p></div><div className="actions">{accounts.data?.length?<select aria-label="Account" value={currentId??''} onChange={e=>{setAccountId(Number(e.target.value));setSnapshotId(null)}}>{accounts.data.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select>:null}{account&&<><button title="Rename account" onClick={rename}><Pencil/>Rename</button><button title="Delete account" className="danger" onClick={removeAccount}><Trash2/>Delete</button></>}<button onClick={()=>chooseImport(true)} disabled={inspect.isPending}><FolderOpen/>Folder</button><button className="primary" onClick={()=>chooseImport()} disabled={inspect.isPending}><FolderOpen/>Import ZIP</button></div></header>
 {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {preview&&<div className="notice"><div><strong>Ready to import {preview.sourceName}</strong><span>{preview.followers.toLocaleString()} followers, {preview.following.toLocaleString()} following{preview.warnings.length?` · ${preview.warnings.join(' · ')}`:''}</span></div><div className="actions"><input aria-label="Archive owner username" placeholder="Owner username" value={ownerUsername} readOnly={!!preview.detectedUsername} onChange={e=>setOwnerUsername(e.target.value)}/>{currentId&&<select aria-label="Import destination" value={importTarget} onChange={e=>setImportTarget(e.target.value as 'current'|'new')}><option value="current">Add snapshot to selected account</option><option value="new">Create new account</option></select>}{importTarget==='new'&&<input aria-label="New account label" placeholder="Account label" value={newLabel} onChange={e=>setNewLabel(e.target.value)}/>}<button onClick={cancelPreview}>Cancel</button><button className="primary" onClick={()=>commit.mutate()} disabled={commit.isPending||!validInstagramUsername(ownerUsername)}>Confirm import</button></div></div>}
 {view==='fame'?<section className="roadmap"><div className="roadmap-title"><Sparkles/><div><h2>Fame privacy engineering</h2><p>Architecture frozen · retrieval intentionally unavailable</p></div></div><div className="status-card"><strong>What exists today</strong><ul>{fame.data?.completedFoundations.map(x=><li key={x}>{x}</li>)}</ul></div><div className="status-card blocked"><strong>Production gates still blocked</strong><ul>{fame.data?.blockedGates.map(x=><li key={x}>{x}</li>)}</ul></div><p className="roadmap-note">No Instagram request, credential, username, or private workload leaves this app. A network retrieval control will not appear until every documented feasibility and independent-audit gate passes.</p></section>:selected?<><section className="metrics">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="workspace"><div className="toolbar"><div className="tabs">{kinds.map(([id,label])=><button className={kind===id?'active':''} onClick={()=>setKind(id)} key={id}>{label}</button>)}</div><div className="tools"><label><Search/><input aria-label="Search username" placeholder="Search username" value={search} onChange={e=>setSearch(e.target.value)}/></label><button title="Export CSV" onClick={()=>exportRows('csv')}><Download/>CSV</button><button title="Export JSON" onClick={()=>exportRows('json')}><Download/>JSON</button></div></div>
 <div className="table"><div className="thead"><span>Account</span><span>{view==='changes'?'Change':'Relationship'}</span></div>{view==='changes'&&!previous?<div className="empty">This is the oldest snapshot. Select a newer snapshot to compare it with the immediately prior import.</div>:(view==='changes'?filteredChanges:rows.data??[]).map((r:any)=><div className="tr" key={`${r.username}-${r.direction??''}`}><div className="account"><div className="avatar">{r.username.slice(0,2).toUpperCase()}</div><div><strong>@{r.username}</strong>{r.profileUrl&&<span>Instagram profile</span>}</div></div><span className={`badge ${r.direction??''}`}>{r.direction??kinds.find(x=>x[0]===r.kind)?.[1]??r.kind}</span></div>)}{(view==='lists'&&rows.data?.length===0)||(view==='changes'&&previous&&filteredChanges.length===0)?<div className="empty">No matching accounts.</div>:null}</div></section>
 <section className="snapshots"><h2>Import history</h2>{snapshots.data?.map(s=><div className={s.id===snapshotId?'selected':''} key={s.id}><button className="snapshot-select" onClick={()=>setSnapshotId(s.id)}><strong>{new Date(s.importedAt).toLocaleString()}</strong><span>{s.followers} followers · {s.following} following</span></button><button title="Delete snapshot" onClick={()=>removeSnapshot(s.id)}><Trash2/></button></div>)}</section></>:<section className="welcome"><BarChart3/><h2>Your audience, clearly mapped</h2><p>Import a complete JSON archive from Instagram Accounts Center. Your data stays on this device.</p><div className="actions"><button onClick={()=>chooseImport(true)}><FolderOpen/>Choose folder</button><button className="primary" onClick={()=>chooseImport()}><FolderOpen/>Choose ZIP</button></div></section>}</main></div>
}
